# ZMK Studio configuration
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n

# RGB underglow configuration
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
# Turn off RGB when keyboard enters idle state
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y


# OLED display configuration
CONFIG_ZMK_DISPLAY=y
# Enable useful OLED widgets for left half
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y
CONFIG_ZMK_WIDGET_LAYER_STATUS=y
CONFIG_ZMK_WIDGET_PERIPHERAL_STATUS=y
# Fun animations (choose one or comment out both)
#CONFIG_ZMK_WIDGET_BONGO_CAT=y
#CONFIG_ZMK_WIDGET_LUNA=y
